import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent
import java.io.File

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

// Development signing is deliberately opt-in and supplied out-of-band. This
// keeps private key material out of Git while allowing local builds and CI to use
// the same certificate. With no credentials present, AGP's normal debug signing
// remains the fallback for first-time setup.
val developmentKeystore = providers.gradleProperty("shakeit.dev.keystore")
    .orElse(providers.environmentVariable("SHAKEIT_DEV_KEYSTORE"))
    .orNull
val developmentStorePassword = providers.gradleProperty("shakeit.dev.storePassword")
    .orElse(providers.environmentVariable("SHAKEIT_DEV_STORE_PASSWORD"))
    .orNull
val developmentKeyAlias = providers.gradleProperty("shakeit.dev.keyAlias")
    .orElse(providers.environmentVariable("SHAKEIT_DEV_KEY_ALIAS"))
    .orNull
val developmentKeyPassword = providers.gradleProperty("shakeit.dev.keyPassword")
    .orElse(providers.environmentVariable("SHAKEIT_DEV_KEY_PASSWORD"))
    .orNull
val hasDevelopmentSigning = !developmentKeystore.isNullOrBlank() &&
    File(developmentKeystore!!).exists() &&
    !developmentStorePassword.isNullOrBlank() &&
    !developmentKeyAlias.isNullOrBlank() &&
    !developmentKeyPassword.isNullOrBlank()

val releaseKeystore = providers.gradleProperty("shakeit.release.keystore")
    .orElse(providers.environmentVariable("SHAKEIT_RELEASE_KEYSTORE"))
    .orNull
val releaseStorePassword = providers.gradleProperty("shakeit.release.storePassword")
    .orElse(providers.environmentVariable("SHAKEIT_RELEASE_STORE_PASSWORD"))
    .orNull
val releaseKeyAlias = providers.gradleProperty("shakeit.release.keyAlias")
    .orElse(providers.environmentVariable("SHAKEIT_RELEASE_KEY_ALIAS"))
    .orNull
val releaseKeyPassword = providers.gradleProperty("shakeit.release.keyPassword")
    .orElse(providers.environmentVariable("SHAKEIT_RELEASE_KEY_PASSWORD"))
    .orNull
val hasReleaseSigning = !releaseKeystore.isNullOrBlank() &&
    File(releaseKeystore!!).exists() &&
    !releaseStorePassword.isNullOrBlank() &&
    !releaseKeyAlias.isNullOrBlank() &&
    !releaseKeyPassword.isNullOrBlank()

val releaseVersionName = providers.gradleProperty("release.versionName").orNull
val releaseVersionCode = providers.gradleProperty("release.versionCode").orNull

android {
    namespace = "com.shakeit"
    compileSdk = 36

    signingConfigs {
        if (hasDevelopmentSigning) {
            create("development") {
                storeFile = File(developmentKeystore!!)
                storePassword = developmentStorePassword
                keyAlias = developmentKeyAlias
                keyPassword = developmentKeyPassword
            }
        }
        if (hasReleaseSigning) {
            create("releaseSigning") {
                storeFile = File(releaseKeystore!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
            }
        }
    }

    defaultConfig {
        applicationId = "com.shakeit"
        minSdk = 24
        targetSdk = 34
        versionCode = releaseVersionCode?.toIntOrNull() ?: 1
        versionName = releaseVersionName ?: "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        getByName("debug") {
            if (hasDevelopmentSigning) {
                signingConfig = signingConfigs.getByName("development")
            }
        }
        getByName("release") {
            if (hasReleaseSigning) {
                signingConfig = signingConfigs.getByName("releaseSigning")
            }
        }
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }

    lint {
        // Lint writes its findings to files rather than to the console, so all
        // three reports are produced and CI splices the text one into the build
        // log it parses. (`textOutput` is a File? here, and the "stdout" trick
        // only exists in the Groovy DSL.)
        textReport = true
        xmlReport = true
        htmlReport = true
        // Lint errors fail the build; warnings are surfaced but tolerated. This
        // project pins targetSdk 34 by design and the Play deadline check is an
        // error, so it is the one check switched off here.
        abortOnError = true
        warningsAsErrors = false
        disable += "ExpiredTargetSdkVersion"
    }
}

// Print every unit-test result and the full stack trace of failures. The CI
// report job parses these lines, so a silent "there were failing tests" is not
// enough to tell an agent what broke.
tasks.withType<Test>().configureEach {
    testLogging {
        events(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
        exceptionFormat = TestExceptionFormat.FULL
        showStackTraces = true
        showStandardStreams = false
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation("androidx.compose.material:material-icons-extended")

    // Optional at runtime and the only privileged path in the app: when Shizuku
    // is absent everything degrades to what standard Android allows, and the UI
    // says so rather than claiming a connection it does not have.
    implementation(libs.shizuku.api)
    implementation(libs.shizuku.provider)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    // JVM-only unit tests for the pure maths behind the blob and the wobble.
    testImplementation(libs.junit)
}
