import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.shakeit"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.shakeit"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }

    lint {
        // Lint writes its findings to files rather than to the console, so all
        // three reports are produced and CI splices the text one into the build
        // log it parses. (`textOutput` is a File? here, and the "stdout" trick
        // only exists in the Groovy DSL.)
        textReport = true
        xmlReport = true
        htmlReport = true
        // Lint errors fail the build; warnings are surfaced but tolerated. This
        // project pins targetSdk 34 by design and the Play deadline check is an
        // error, so it is the one check switched off here.
        abortOnError = true
        warningsAsErrors = false
        disable += "ExpiredTargetSdkVersion"
    }
}

// Print every unit-test result and the full stack trace of failures. The CI
// report job parses these lines, so a silent "there were failing tests" is not
// enough to tell an agent what broke.
tasks.withType<Test>().configureEach {
    testLogging {
        events(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
        exceptionFormat = TestExceptionFormat.FULL
        showStackTraces = true
        showStandardStreams = false
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation("androidx.compose.material:material-icons-extended")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    // JVM-only unit tests for the pure maths behind the blob and the wobble.
    testImplementation(libs.junit)
}
